In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
model = nn.Linear(4, 1)
optimizer = optim.Adam(model.parameters(), lr=0.01)
model

Linear(in_features=4, out_features=1, bias=True)

In [ ]:
state_dict = model.state_dict()
state_dict

OrderedDict([('weight', tensor([[ 0.0555,  0.2672, -0.2744,  0.3406]])),
             ('bias', tensor([0.3496]))])

In [ ]:
weights = state_dict['weight']
weights

tensor([[ 0.0555,  0.2672, -0.2744,  0.3406]])

In [ ]:
bias = state_dict['bias']
bias

tensor([0.3496])

In [ ]:
loss_func = nn.MSELoss()
loss_func

MSELoss()

In [ ]:
x = torch.rand(4)
x

tensor([0.2155, 0.9721, 0.2278, 0.6490])

In [ ]:
y = model(x)
y

tensor([0.7798], grad_fn=<AddBackward0>)

In [ ]:
target = y.clone().detach() * 5 + 1.1
y = torch.tensor(y, requires_grad=True)
loss = loss_func(y, target)
loss

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


tensor(17.8010, grad_fn=<MseLossBackward>)

In [ ]:
print(weights.grad, weights.is_leaf)
print(bias.grad, bias.is_leaf)
print(loss.grad, loss.is_leaf)
print(y.grad, y.is_leaf)

None True
None True
None False
None True


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
loss.backward(retain_graph=True)

In [ ]:
print(weights.grad, weights.is_leaf)
print(bias.grad, bias.is_leaf)
print(loss.grad, loss.is_leaf)
print(y.grad, y.is_leaf)

None True
None True
None False
tensor([-8.4382]) True


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
state_dict = model.state_dict()
print(state_dict)
print(model.parameters())

OrderedDict([('weight', tensor([[ 0.0555,  0.2672, -0.2744,  0.3406]])), ('bias', tensor([0.3496]))])
<generator object Module.parameters at 0x7fe25cc30c50>


In [ ]:
optimizer.step()

In [ ]:
state_dict = model.state_dict()
print(state_dict)
print(model.parameters())

OrderedDict([('weight', tensor([[ 0.0555,  0.2672, -0.2744,  0.3406]])), ('bias', tensor([0.3496]))])
<generator object Module.parameters at 0x7fe25cc30a50>
